import type { Country } from "./country";

const wikimediaFlagUrl = (fileName: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${fileName}`;

export const countryFixtures = [
  {
    code: "US",
    name: "United States",
    capital: "Washington, D.C.",
    factSnippet: "Runs on road trips, diner coffee, and heroic snack aisles.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20the%20United%20States.svg"),
    likes: 842,
    dislikes: 318,
  },
  {
    code: "CA",
    name: "Canada",
    capital: "Ottawa",
    factSnippet: "Maple syrup energy with apology-tier customer support.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20Canada.svg"),
    likes: 731,
    dislikes: 112,
  },
  {
    code: "BR",
    name: "Brazil",
    capital: "Brasilia",
    factSnippet: "Carnival volume, beach mode, and football takes at full power.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20Brazil.svg"),
    likes: 689,
    dislikes: 246,
  },
  {
    code: "JP",
    name: "Japan",
    capital: "Tokyo",
    factSnippet: "Vending machines, bullet trains, and stationery with main-character energy.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20Japan.svg"),
    likes: 917,
    dislikes: 87,
  },
  {
    code: "IN",
    name: "India",
    capital: "New Delhi",
    factSnippet: "Spice levels, cinema drama, and group chats moving at light speed.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20India.svg"),
    likes: 803,
    dislikes: 291,
  },
  {
    code: "ZA",
    name: "South Africa",
    capital: "Pretoria",
    factSnippet: "Braai smoke, big views, and eleven-language flexing.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20South%20Africa.svg"),
    likes: 456,
    dislikes: 233,
  },
  {
    code: "DE",
    name: "Germany",
    capital: "Berlin",
    factSnippet: "Good beer, tidy queues, and order engineered to three decimals.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20Germany.svg"),
    likes: 764,
    dislikes: 149,
  },
  {
    code: "FR",
    name: "France",
    capital: "Paris",
    factSnippet: "Pastry confidence, museum stamina, and espresso-sized debates.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20France.svg"),
    likes: 592,
    dislikes: 305,
  },
  {
    code: "GB",
    name: "United Kingdom",
    capital: "London",
    factSnippet: "Tea logistics, weather commentary, and queue discipline as art.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20the%20United%20Kingdom.svg"),
    likes: 618,
    dislikes: 276,
  },
  {
    code: "AU",
    name: "Australia",
    capital: "Canberra",
    factSnippet: "Beach confidence, flat whites, and wildlife with boss-fight energy.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20Australia.svg"),
    likes: 704,
    dislikes: 134,
  },
  {
    code: "MX",
    name: "Mexico",
    capital: "Mexico City",
    factSnippet: "Taco precision, mural swagger, and sauces that check your ego.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20Mexico.svg"),
    likes: 477,
    dislikes: 198,
  },
  {
    code: "EG",
    name: "Egypt",
    capital: "Cairo",
    factSnippet: "Ancient monuments, river views, and history refusing to be background.",
    flagImageUrl: wikimediaFlagUrl("Flag%20of%20Egypt.svg"),
    likes: 389,
    dislikes: 221,
  },
] as const satisfies readonly Country[];
